### ISSUE TITLE
Sequence

### ISSUE THREAD

**Issue by skealy** [GuillaumeLazar/qtrb#2]
Having reviewed the content I have a question.
I assume you intend the scripts to be run in the numbered sequence 10... followed by 20... etc.
In 50.. you copy $ROOT_DIR/qt5pi to the mounted sysroot directory and then without doing anything further you unmount sysroot in 60...
What purpose does this serve?

**Comment by GuillaumeLazar** [comment]
First of all, these scripts are my personal helpers to generate a QTRB release. You don't need to use it, you can directly download and use [the binary release files of QTRB](https://github.com/GuillaumeLazar/qtrb/releases).

If you want to build Qt  yourself for a Raspberry Pi, here are some explanations:
- The number in the filenames is a family type of the operation. (download = 1X, build=4X, ...)
- It's also more or less a hint of the process order. You do the "download" step before the "build". But it's not an absolute rule.
- When the  cross-compiled Qt for Rpi is copied on the mounted sysroot then you can unmount it. The .img file is ready to be copied on your sdcard (check the script step 80).

**Comment by skealy** [comment]
Thank you for your response.
I have successfully used your scripts to build the img file, load it on the SD card and run a compiled Qt widget application on a Raspberry Pi3. I am encountering the EGLFS issue "unable to query physical screen size which I am still attempting to resolve. 
In order to set up Qt Creator I needed to identify a sysroot directory in the Kit configuration. As sysroot is unmounted by 60_unmount_sysroot.sh I now run 20_mount_sysroot.sh before running QtCreator and set the sysroot directory to /opt/qtrb/sysroot in the kit. 
I am not sure if this is what you intended but it appears to work.
Incidentally I did not find any reference in your scripts to downloading and running sysroot-relativelinks.py on the mounted sysroot directory. The make install produces errors if this step is not performed before compiling. I am running Debian Stretch on my host computer.
Congratulations on your excellent work!

**Comment by GuillaumeLazar** [comment]
- The message "EGLFS issue "unable to query physical screen size which I am still attempting to resolve." is just a warning. You should define the 2 export the two variables depending you screen size. Check the video https://youtu.be/YYOjdwT5UuQ?t=226 (it's about QTRPI, not QTRB but the information are the same)
- Concerning the sysroot and Qt creator, you're right. You need to mount it to be able to cross-compile an Qt application from your host computer. Check the video https://youtu.be/1d2bh7iUKNc?list=PLFsidzAJDEbBr3l0BNMDcDQlUM04GRlf2 some path should be adapted for QTRB
- Thanks for your remark concerning the file "sysroot-relativelinks.py". Yes, this manual step must be done before building Qt on your computer. I guess it will help the issue #1.

Many thanks :+1:
