### ISSUE TITLE
Unknown module(s) in QT: quick

### ISSUE THREAD

**Issue by jppinget** [GuillaumeLazar/qtrb#3]
Hello,

I successfully installed and compiled qtrb. 

I tried to create a simple project with qtcreator 4.5. 

I have an error when trying to compile : 

Unknown module(s) in QT: quick

Someone knows how to fix that ?

**Comment by jppinget** [comment]
I tried to rerun ./20_mount_sysroot.sh and then : ```sudo ./sysroot-relativelinks.py /opt/qtrb/sysroot/```but I got this error : 

```
OSError : [Errno 1] Operation not permitted: '/opt/qtrb/sysroot/proc/1/exe'
```

**Comment by GuillaumeLazar** [comment]
Hello,

You should try to use the precompiled binaries, check the [Release](https://github.com/GuillaumeLazar/qtrb/releases) page. This version comes with a lot of Qt modules (Core, Gui, Widgets, Network, Qml, QuickControls2, ...)

Once it's working with the precompiled, you can try to compile it yourself. If you got any issues you will be able to swap some items (your version with the precompiled one) to investigate on your issue.

**Comment by GuillaumeLazar** [comment]
* I put some documentation on the [Wiki](https://github.com/GuillaumeLazar/qtrb/wiki). 
* You should **NOT** run the sysroot-relativelinks script each time (only one time if you create the sysroot yourself)
* Try to compile from CLI (/opt/qtrb/qt-linux-rasp-pi3/bin/qmake) then you can go ahead and configure Qt Creator
